// GETS
const GET_PRODUCTS = 'GET_PRODUCTS';
const GET_PRODUCTS_DETAILS = 'GET_PRODUCTS_DETAILS';
const GET_USERS = 'GET_USERS';

const RATE_PRODUCT = "RATE_PRODUCT";

// CATEGORIES
const GET_CATEGORIES = 'GET_CATEGORIES';

//LIMPIA ESTADO
const UNMOUNT_GET = 'UNMOUNT_GET';

// SETEADORES DE ESTADO 
const SET_PAGE = "SET_PAGE";
const SET_CATEGORY = "SET_CATEGORY";

//CARRITO
const ADD_CART ="ADD_CART";
const GET_CART ="GET_CART";
const DELETE_CART_ITEM= "DELETE_CART_ITEM";
const DELETE_CART_ALL= "DELETE_CART_ALL";
const DELETE_CART_ONE="DELETE_CART_ONE";
const SET_TOTAL = "SET_TOTAL";

const SET_MODAL = "SET_MODAL";

// ORDER

//USER
const AUTH="AUTH";
const LOGOUT= "LOGOUT";
const REGISTER_LOCAL= "REGISTER_LOCAL";
const LOGIN_GOOGLE = "LOGIN_GOOGLE";
const LOGIN_LOCAL = "LOGIN_LOCAL";
const CHANGE_USER_ROLE = "CHANGE_USER_ROLE"
const EDIT_DATE_PROFILE = "EDIT_DATE_PROFILE";

// TICKETS
const CREATE_TICKET = "CREATE_TICKET";
const GET_TICKETS = "GET_TICKETS";
const GET_TICKETS_ADMIN = "GET_TICKETS_ADMIN"
const DELETE_TICKET = "DELETE_TICKET"
const CHANGE_TICKET_STATUS = "CHANGE_TICKET_STATUS"

// PAGO
const DATOS_COMPRA = "DATOS_COMPRA";

//ADMIN

const CREATE_ITEM = "CREATE_ITEM";
const DELETE_ITEM = "DELETE_ITEM";
const GET_ADMIN_ITEMS = "GET_ADMIN_ITEMS"
const SET_ITEM = "SET_ITEM"

module.exports = {
    GET_PRODUCTS,
    GET_PRODUCTS_DETAILS,
    GET_CATEGORIES,
    UNMOUNT_GET,
    SET_PAGE,
    SET_CATEGORY,
    RATE_PRODUCT,
    ADD_CART,
    GET_CART,
    DELETE_CART_ITEM,
    SET_MODAL,
    AUTH,
    LOGOUT,
    REGISTER_LOCAL,
    GET_TICKETS,
    GET_TICKETS_ADMIN,
    CREATE_TICKET,
    LOGIN_GOOGLE,
    SET_TOTAL,
    DATOS_COMPRA,
    DELETE_TICKET,
    CHANGE_TICKET_STATUS,
    LOGIN_LOCAL,
    CHANGE_USER_ROLE,
    GET_USERS,
    CREATE_ITEM,
    EDIT_DATE_PROFILE,
    DELETE_ITEM,
    GET_ADMIN_ITEMS,
    SET_ITEM,
    DELETE_CART_ALL,
    DELETE_CART_ONE
}