// GETS
const GET_PRODUCTS = 'GET_PRODUCTS';
const GET_PRODUCTS_DETAILS = 'GET_PRODUCTS_DETAILS';

const RATE_PRODUCT = "RATE_PRODUCT";

// CATEGORIES
const GET_CATEGORIES = 'GET_CATEGORIES';

//LIMPIA ESTADO
const UNMOUNT_GET = 'UNMOUNT_GET';

// SETEADORES DE ESTADO 
const SET_PAGE = "SET_PAGE";
const SET_CATEGORY = "SET_CATEGORY";

//CARRITO
const ADD_CART ="ADD_CART";
const GET_CART ="GET_CART";
const DELETE_CART_ITEM= "DELETE_CART_ITEM";
const SET_TOTAL = "SET_TOTAL";

const SET_MODAL = "SET_MODAL";

// ORDER

//USER
const AUTH="AUTH";
const LOGOUT= "LOGOUT";
const REGISTER_LOCAL= "REGISTER_LOCAL";
const LOGIN_GOOGLE = "LOGIN_GOOGLE";
const LOGIN_LOCAL = "LOGIN_LOCAL";

// TICKETS
const CREATE_TICKET = "CREATE_TICKET";
const GET_TICKETS = "GET_TICKETS";


module.exports = {
    GET_PRODUCTS,
    GET_PRODUCTS_DETAILS,
    GET_CATEGORIES,
    UNMOUNT_GET,
    SET_PAGE,
    SET_CATEGORY,
    RATE_PRODUCT,
    ADD_CART,
    GET_CART,
    DELETE_CART_ITEM,
    SET_MODAL,
    AUTH,
    LOGOUT,
    REGISTER_LOCAL,
    GET_TICKETS,
    CREATE_TICKET,
    LOGIN_GOOGLE,
    SET_TOTAL,
    LOGIN_LOCAL
}